import { describe, expect, it, vi } from "vitest";
import { applyMemoryResolution } from "../../src/main/memory/memory-resolution-applier.js";
import type { MemoryStore } from "../../src/main/memory/memory-store.js";
import { createEmptyMemoryFileV2, type ConflictLog, type L2MemoryV2, type MemoryFile } from "../../src/main/memory/memory-types.js";
import type { MemoryResolution } from "../../src/main/memory/memory-resolver.js";

const TIME = "2026-07-15T00:00:00.000Z";
function memory(id: string, updates: Partial<L2MemoryV2> = {}): L2MemoryV2 { return { id, content: id, confidence: 0.9, importance: "medium", evidenceIds: [`e-${id}`], createdAt: TIME, updatedAt: TIME, lastAccessedAt: TIME, accessCount: 0, weight: 0.8, isPinned: false, isEnabled: true, status: "active", syncStatus: "synced", isSummary: false, sourceMemoryIds: [], sourceSnapshots: [], conflictWith: [id === "new" ? "old" : "new"], ...updates }; }
function createStore(initial: MemoryFile) { let value = structuredClone(initial); const store: MemoryStore & { updates: number; beforeUpdate?: (draft: MemoryFile) => void; read: () => MemoryFile } = { updates: 0, load: vi.fn(async () => structuredClone(value)), async update(mutator) { store.updates += 1; const draft = structuredClone(value); store.beforeUpdate?.(draft); mutator(draft); value = draft; return structuredClone(value); }, read: () => structuredClone(value) }; return store; }
function setup(overrides: Partial<ConflictLog> = {}, memoryUpdates: readonly [Partial<L2MemoryV2>, Partial<L2MemoryV2>] = [{}, {}]) { const source = memory("new", memoryUpdates[0]); const target = memory("old", memoryUpdates[1]); const log: ConflictLog = { id: "c1", sourceMemoryId: "new", targetMemoryId: "old", createdAt: TIME, status: "processing", score: 90, priority: "high", attempts: 0, signals: {}, ...overrides }; const file: MemoryFile = { ...createEmptyMemoryFileV2(), l2: [source, target], evidence: [source, target].map((item) => ({ id: `e-${item.id}`, memoryId: item.id, quote: item.content, capturedAt: TIME, source: "conversation", sourceMemoryIds: [] })), conflictLogs: [log] }; return { store: createStore(file), source, target, log }; }
function resolution(resolutionType: MemoryResolution["resolutionType"], actions: MemoryResolution["actions"], confidence = 0.9): MemoryResolution { return { resolutionType, sourceMemoryId: "new", targetMemoryId: "old", status: resolutionType === "uncertain" ? "uncertain" : "resolved", confidence, reason: "approved", actions }; }
async function apply(store: MemoryStore, source: L2MemoryV2, target: L2MemoryV2, log: ConflictLog, result: MemoryResolution) { return applyMemoryResolution({ store, conflict: log, source, target, sourceEvidenceIds: [...source.evidenceIds], targetEvidenceIds: [...target.evidenceIds], resolution: result, now: () => new Date(TIME), idFactory: () => "audit-1" }); }

describe("applyMemoryResolution", () => {
  it.each(["unrelated", "context_difference"] as const)("keeps both active and resolves a %s conflict atomically", async (resolutionType) => { const { store, source, target, log } = setup(); await expect(apply(store, source, target, log, resolution(resolutionType, ["keep_both"]))).resolves.toMatchObject({ applied: true }); const saved = store.read(); expect(store.updates).toBe(1); expect(saved.l2.map((item) => item.status)).toEqual(["active", "active"]); expect(saved.l2.map((item) => item.conflictWith)).toEqual([[], []]); expect(saved.conflictLogs[0]).toMatchObject({ status: "resolved", resolutionType }); expect(saved.auditLogs).toEqual([expect.objectContaining({ id: "audit-1", source: "automatic", result: "success", targetId: "c1" })]); });

  it("supersedes the older unpinned target for preference evolution", async () => { const { store, source, target, log } = setup(); await apply(store, source, target, log, resolution("preference_evolution", ["supersede_target"])); const saved = store.read(); expect(saved.l2[1]).toMatchObject({ status: "superseded", isEnabled: false, supersededBy: "new" }); expect(saved.l2[0]).toMatchObject({ status: "active", conflictWith: [] }); expect(saved.conflictLogs[0]?.status).toBe("resolved"); });

  it("applies a direct conflict only with sufficient confidence, complete evidence, unchanged snapshots, and an unpinned target", async () => { const { store, source, target, log } = setup(); await apply(store, source, target, log, resolution("direct_conflict", ["supersede_target"], 0.85)); expect(store.read().l2[1]?.status).toBe("superseded"); const guardedCases: Array<[number, [Partial<L2MemoryV2>, Partial<L2MemoryV2>]]> = [[0.84, [{}, {}]], [0.9, [{ evidenceIds: [] }, {}]], [0.9, [{}, { isPinned: true }]]]; for (const [confidence, updates] of guardedCases) { const fixture = setup({}, updates); await apply(fixture.store, fixture.source, fixture.target, fixture.log, resolution("direct_conflict", ["supersede_target"], confidence)); expect(fixture.store.read().l2.map((item) => item.status)).toEqual(["active", "active"]); expect(fixture.store.read().conflictLogs[0]?.status).toBe("uncertain"); } });

  it("keeps both memories and marks uncertain results without modifying timestamps", async () => { const { store, source, target, log } = setup(); await apply(store, source, target, log, resolution("uncertain", ["mark_uncertain"])); const saved = store.read(); expect(saved.l2.map((item) => item.updatedAt)).toEqual([TIME, TIME]); expect(saved.conflictLogs[0]).toMatchObject({ status: "uncertain", resolutionType: "uncertain", finishedAt: TIME }); });

  it("downgrades every pinned destructive target to uncertain", async () => { const { store, source, target, log } = setup({}, [{ isPinned: true }, {}]); await apply(store, source, target, log, resolution("preference_evolution", ["supersede_source"])); const saved = store.read(); expect(saved.l2.map((item) => item.status)).toEqual(["active", "active"]); expect(saved.conflictLogs[0]).toMatchObject({ status: "uncertain", resolutionType: "uncertain" }); });

  it("rejects stale, missing, and unrelated resolutions with no update or partial write", async () => { const { store, source, target, log } = setup(); store.beforeUpdate = (draft) => { draft.l2[1]!.updatedAt = "2026-07-16T00:00:00.000Z"; }; await expect(apply(store, source, target, log, resolution("preference_evolution", ["supersede_target"]))).resolves.toMatchObject({ applied: false, code: "stale" }); expect(store.read().l2[1]?.status).toBe("active"); const unrelated = setup(); await expect(apply(unrelated.store, unrelated.source, unrelated.target, unrelated.log, { ...resolution("unrelated", ["keep_both"]), sourceMemoryId: "other" })).resolves.toMatchObject({ applied: false, code: "invalid_resolution" }); expect(unrelated.store.updates).toBe(0); });
});
